spring.application.name=DSA

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

piston.api.base-url=${piston.base-url}
piston.api.execute-endpoint=/api/v2/execute
piston.api.runtimes-endpoint=/api/v2/runtimes

ai.api.key=${GEMINI_API_KEY}
ai.api.base-url=https://generativelanguage.googleapis.com
ai.api.model=gemini-3.6-flash
ai.api.timeout=60s

spring.jpa.hibernate.ddl-auto=update

spring.jpa.properties.hibernate.format_sql=true