spring.application.name=DSA

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

piston.api.base-url=${piston.base-url}
piston.api.execute-endpoint=/api/v2/execute
piston.api.runtimes-endpoint=/api/v2/runtimes

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.jpa.properties.hibernate.format_sql=true